"""create_todos_table

Revision ID: 9a93d72949c7
Revises:
Create Date: 2026-04-04 21:09:56.518393

Creates the initial ``todos`` table.

Data-loss risk:
    downgrade() drops the ``todos`` table and all its rows permanently.
    Only run downgrade() in development or when the table is known to be empty.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '9a93d72949c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing surrogate key (SQL Server IDENTITY).'),
    sa.Column('title', sa.NVARCHAR(length=200), nullable=False, comment='Short title of the todo item (max 200 characters).'),
    sa.Column('description', sa.NVARCHAR(length=1000), nullable=True, comment='Optional longer description (max 1 000 characters).'),
    sa.Column('is_completed', mssql.BIT(), server_default='0', nullable=False, comment='Whether the todo has been completed.'),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('GETUTCDATE()'), nullable=False, comment='UTC timestamp of record creation (set by database).'),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('GETUTCDATE()'), nullable=False, comment='UTC timestamp of last update (maintained by database/ORM).'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
