"""add_categories_table_and_category_id_to_todos

Revision ID: b804531938a7
Revises: 9a93d72949c7
Create Date: 2026-04-07 19:39:32.987809

Creates the ``categories`` lookup table and wires ``todos.category_id`` to it
via a nullable foreign key with ON DELETE SET NULL.

Data-loss risk:
    downgrade() drops ``todos.category_id`` (data loss for any assigned
    categories) and then drops the entire ``categories`` table (all category
    rows are permanently deleted).
    Only run downgrade() in development or when both tables are known to be empty.

Case-insensitive uniqueness:
    The ``uq_categories_name`` unique constraint relies on SQL Server's default
    case-insensitive collation (SQL_Latin1_General_CP1_CI_AS).  If the database
    was created with a case-sensitive collation, add a computed-column unique
    index manually.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'b804531938a7'
down_revision: Union[str, None] = '9a93d72949c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-incrementing surrogate key (SQL Server IDENTITY).'),
    sa.Column('name', sa.NVARCHAR(length=100), nullable=False, comment='Display name of the category (max 100 characters, unique).'),
    sa.Column('description', sa.NVARCHAR(length=500), nullable=True, comment='Optional description of the category (max 500 characters).'),
    sa.Column('created_at', mssql.DATETIME2(), server_default=sa.text('getutcdate()'), nullable=False, comment='UTC timestamp of record creation (set by database).'),
    sa.Column('updated_at', mssql.DATETIME2(), server_default=sa.text('getutcdate()'), nullable=False, comment='UTC timestamp of last update (maintained by database/ORM).'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_categories_name'),
    comment='Lookup table of categories that can be assigned to todos.'
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.add_column('todos', sa.Column('category_id', sa.Integer(), nullable=True, comment='FK to categories.id; NULL when no category is assigned.'))
    op.create_index(op.f('ix_todos_category_id'), 'todos', ['category_id'], unique=False)
    op.create_foreign_key(
        'fk_todos_category_id_categories',
        'todos', 'categories',
        ['category_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop FK before the column, and the column before the referenced table.
    op.drop_constraint('fk_todos_category_id_categories', 'todos', type_='foreignkey')
    op.drop_index(op.f('ix_todos_category_id'), table_name='todos')
    op.drop_column('todos', 'category_id')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
